using System.Text.RegularExpressions;

namespace FilamentDbApp.Services.Website;

public sealed class WebsiteHtmlRendererService
{
    public string RenderMainWebsite(string template, string dataJson, DateTime generatedAt, bool isProduction, string buildLabel)
    {
        if (string.IsNullOrWhiteSpace(template))
        {
            throw new InvalidOperationException("Website template is empty.");
        }

        if (string.IsNullOrWhiteSpace(dataJson))
        {
            throw new InvalidOperationException("Website DATA payload is empty.");
        }

        var outputKind = isProduction ? "production file: index.html" : "safe preview file: index-test.html";
        var generatedNote = $"<!-- Generated by 3DPIceland Filament DB {buildLabel} at {generatedAt:yyyy-MM-dd HH:mm:ss}. {outputKind}. -->\n";
        var updated = ReplaceDataBlock(template, dataJson);
        updated = RemoveLegacyPricingOverlay(updated);
        return generatedNote + updated;
    }

    private static string RemoveLegacyPricingOverlay(string template)
    {
        // v35.0 initially added pricing through a static PRICE_DATA object followed by
        // Object.assign(...). Native website DATA now carries the current pricing fields.
        // Keeping that legacy overlay would overwrite freshly exported prices with stale
        // values from the selected external template. Remove both pieces when present.
        var priceStart = Regex.Match(template, @"\bconst\s+PRICE_DATA\s*=");
        if (priceStart.Success)
        {
            var equalsIndex = template.IndexOf('=', priceStart.Index);
            var objectStart = equalsIndex >= 0 ? template.IndexOf('{', equalsIndex) : -1;
            var objectEnd = objectStart >= 0 ? FindMatchingJsonObjectEnd(template, objectStart) : -1;

            if (objectEnd >= 0)
            {
                var replaceEnd = objectEnd + 1;
                while (replaceEnd < template.Length && char.IsWhiteSpace(template[replaceEnd])) replaceEnd++;
                if (replaceEnd < template.Length && template[replaceEnd] == ';') replaceEnd++;
                while (replaceEnd < template.Length && (template[replaceEnd] == '\r' || template[replaceEnd] == '\n')) replaceEnd++;
                template = template.Substring(0, priceStart.Index) + template.Substring(replaceEnd);
            }
        }

        template = Regex.Replace(
            template,
            @"^[ \t]*Object\.values\(DATA\)\.forEach\(rows=>rows\.forEach\(r=>Object\.assign\(r,PRICE_DATA\[r\.materialId\]\|\|\{\}\)\)\);[ \t]*(?:\r?\n)?",
            string.Empty,
            RegexOptions.Multiline);

        return template;
    }

    public WebsiteHtmlRendererVerificationResult VerifyMainWebsitePayload(WebsiteChartPayload payload)
    {
        var result = new WebsiteHtmlRendererVerificationResult
        {
            TensileRows = payload.Tensile.Count,
            ImpactRows = payload.Impact.Count,
            StiffnessRows = payload.Stiffness.Count
        };

        result.HasDataPayload = result.TensileRows > 0 && result.ImpactRows > 0 && result.StiffnessRows > 0;
        result.PayloadRowsAligned = result.TensileRows == result.ImpactRows && result.TensileRows == result.StiffnessRows;
        result.HasMaterialIds = payload.Tensile.All(row => row.TryGetValue("materialId", out var value) && !string.IsNullOrWhiteSpace(value?.ToString()));
        result.HasChartMetrics = HasAnyMetric(payload.Tensile, "upright", "flat") ||
                                 HasAnyMetric(payload.Impact, "upright", "flat") ||
                                 HasAnyMetric(payload.Stiffness, "value");
        result.HasPricingFields = payload.Tensile.All(row => row.ContainsKey("msrpUsd") &&
                                                              row.ContainsKey("landedCostUsd") &&
                                                              row.ContainsKey("msrpUsdPerKg") &&
                                                              row.ContainsKey("landedCostUsdPerKg") &&
                                                              row.ContainsKey("pricingStatus"));
        result.TemplateDataBlockSupported = true;
        result.Passed = result.HasDataPayload && result.PayloadRowsAligned && result.HasMaterialIds && result.HasChartMetrics && result.HasPricingFields && result.TemplateDataBlockSupported;
        return result;
    }

    public bool HasDataBlock(string template)
    {
        if (string.IsNullOrEmpty(template)) return false;
        return Regex.IsMatch(template, @"\bconst\s+DATA\s*=");
    }

    private static string ReplaceDataBlock(string template, string dataJson)
    {
        var replacement = "const DATA=" + dataJson + ";";

        var dataStart = Regex.Match(template, @"\bconst\s+DATA\s*=");
        if (!dataStart.Success)
        {
            throw new InvalidOperationException("Could not locate the const DATA=... block in the website template.");
        }

        var equalsIndex = template.IndexOf('=', dataStart.Index);
        if (equalsIndex < 0)
        {
            throw new InvalidOperationException("Could not locate the const DATA=... block in the website template.");
        }

        var objectStart = template.IndexOf('{', equalsIndex);
        if (objectStart < 0)
        {
            throw new InvalidOperationException("Could not locate the opening JSON object for const DATA in the website template.");
        }

        var objectEnd = FindMatchingJsonObjectEnd(template, objectStart);
        if (objectEnd < 0)
        {
            throw new InvalidOperationException("Could not locate the end of the const DATA JSON object in the website template.");
        }

        var replaceEnd = objectEnd + 1;
        while (replaceEnd < template.Length && char.IsWhiteSpace(template[replaceEnd])) replaceEnd++;
        if (replaceEnd < template.Length && template[replaceEnd] == ';') replaceEnd++;

        var lineEnding = Environment.NewLine;
        if (replaceEnd < template.Length && template[replaceEnd] == '\r')
        {
            replaceEnd++;
            if (replaceEnd < template.Length && template[replaceEnd] == '\n') replaceEnd++;
            lineEnding = "\r\n";
        }
        else if (replaceEnd < template.Length && template[replaceEnd] == '\n')
        {
            replaceEnd++;
            lineEnding = "\n";
        }

        return template.Substring(0, dataStart.Index) + replacement + lineEnding + template.Substring(replaceEnd);
    }

    private static int FindMatchingJsonObjectEnd(string text, int objectStart)
    {
        var depth = 0;
        var inString = false;
        var escape = false;

        for (var i = objectStart; i < text.Length; i++)
        {
            var ch = text[i];
            if (inString)
            {
                if (escape) { escape = false; continue; }
                if (ch == '\\') { escape = true; continue; }
                if (ch == '"') inString = false;
                continue;
            }

            if (ch == '"') { inString = true; continue; }
            if (ch == '{') { depth++; continue; }
            if (ch == '}')
            {
                depth--;
                if (depth == 0) return i;
            }
        }

        return -1;
    }

    private static bool HasAnyMetric(IReadOnlyList<Dictionary<string, object?>> rows, params string[] metricKeys)
    {
        return rows.Any(row => metricKeys.Any(key => row.TryGetValue(key, out var value) && IsNumeric(value)));
    }

    private static bool IsNumeric(object? value)
    {
        return value switch
        {
            null => false,
            int => true,
            long => true,
            float f => float.IsFinite(f),
            double d => double.IsFinite(d),
            decimal => true,
            _ => double.TryParse(value.ToString(), out var parsed) && double.IsFinite(parsed)
        };
    }
}

public sealed class WebsiteHtmlRendererVerificationResult
{
    public bool Passed { get; set; }
    public int TensileRows { get; set; }
    public int ImpactRows { get; set; }
    public int StiffnessRows { get; set; }
    public bool HasDataPayload { get; set; }
    public bool PayloadRowsAligned { get; set; }
    public bool HasMaterialIds { get; set; }
    public bool HasChartMetrics { get; set; }
    public bool HasPricingFields { get; set; }
    public bool TemplateDataBlockSupported { get; set; }
}
