using System.Text.RegularExpressions;

using System.Text;

namespace FilamentDbApp.Services.Website;

public sealed class WebsiteHtmlRendererService
{
    public const int MaximumTemplateBytes = 5 * 1024 * 1024;

    public void ValidateTemplateForImport(string template)
    {
        if (string.IsNullOrWhiteSpace(template))
        {
            throw new InvalidOperationException("Website template is empty.");
        }

        if (Encoding.UTF8.GetByteCount(template) > MaximumTemplateBytes)
        {
            throw new InvalidOperationException("Website template exceeds the 5 MiB import limit.");
        }

        if (template.IndexOf('\0') >= 0)
        {
            throw new InvalidOperationException("Website template contains a NUL character and cannot be imported.");
        }

        _ = ReplaceDataBlock(template, "{}");
    }

    public string RenderMainWebsite(string template, string dataJson, DateTime generatedAt, bool isProduction, string buildLabel)
    {
        if (string.IsNullOrWhiteSpace(template))
        {
            throw new InvalidOperationException("Website template is empty.");
        }

        if (string.IsNullOrWhiteSpace(dataJson))
        {
            throw new InvalidOperationException("Website DATA payload is empty.");
        }

        var outputKind = isProduction ? "production file: index.html" : "safe preview file: index-test.html";
        var generatedNote = $"<!-- Generated by 3DPIceland Filament DB {buildLabel} at {generatedAt:yyyy-MM-dd HH:mm:ss}. {outputKind}. -->\n";
        var updated = ReplaceDataBlock(template, dataJson);
        updated = RemoveLegacyPricingOverlay(updated);
        updated = ApplyThermalPresentation(updated);
        return generatedNote + updated;
    }

    private static string ApplyThermalPresentation(string html)
    {
        const string marker = "/* 3DP-THERMAL-PUBLIC-v61.0.7-r3 */";
        if (html.Contains(marker, StringComparison.Ordinal)) return html;

        var replacements = new (string Old, string New)[]
        {
            (
                "marketingName:ref.marketingName,tensileMean,impactMean,stiffness,layerAdhesion,",
                "marketingName:ref.marketingName,thermalResultTemperatureC:ref.thermalResultTemperatureC??null,thermalScore:ref.thermalScore??null,thermalMethodVersion:ref.thermalMethodVersion||null,thermalLimitation:ref.thermalLimitation||null,tensileMean,impactMean,stiffness,layerAdhesion,"),
            (
                "||r.stiffness!=null||r.layerAdhesion!=null);",
                "||r.stiffness!=null||r.layerAdhesion!=null||r.thermalScore!=null);"),
            (
                "stiffnessScore:avg(group.map(x=>x.stiffnessScore)),\n   consistencyScore:",
                "stiffnessScore:avg(group.map(x=>x.stiffnessScore)),\n   thermalScore:avg(group.map(x=>x.thermalScore)),\n   consistencyScore:"),
            (
                "['Stiffness',metricValue(row.stiffnessScore)],\n   ['Consistency'",
                "['Stiffness',metricValue(row.stiffnessScore)],\n   ['Thermal',metricValue(row.thermalScore)],\n   ['Consistency'"),
            (
                "target.innerHTML=radarSvg(selected,'Selected filament')+radarSvg(avgRow,profileAverageSubtitle(profileReinforcementKey(selected.reinforcement)));",
                "target.innerHTML=radarSvg(selected,'Selected filament')+radarSvg(avgRow,profileAverageSubtitle(profileReinforcementKey(selected.reinforcement)))+`<div class=\"value-note\"><strong>Thermal:</strong> ${selected.thermalResultTemperatureC==null?'N/A':fmt(selected.thermalResultTemperatureC)+' °C · '+fmt(selected.thermalScore)+' / 100 · method '+esc(selected.thermalMethodVersion||'not recorded')}<br>${esc(selected.thermalLimitation||'No fixture-specific thermal result is available; no value is inferred.')}</div>`;"),
            (
                "<section class=\"card\"><h2>Young\\'s modulus / stiffness</h2><div class=\"meta\"><span id=\"stiffnessCount\"><a class=\"method-link\" href=\"https://youtu.be/nv9PexjvFRw?si=LypqEKGuhwySrWDq\" rel=\"noopener noreferrer\" target=\"_blank\">Video on my testing method, and mesuring device</a></span></div><div class=\"legend\"><span><i class=\"key single\"></i>Stiffness</span></div><div class=\"scroll\"><div id=\"stiffnessChart\"></div></div></section>",
                "<section class=\"card\"><h2>Young\\'s modulus / stiffness</h2><div class=\"meta\"><span id=\"stiffnessCount\"><a class=\"method-link\" href=\"https://youtu.be/nv9PexjvFRw?si=LypqEKGuhwySrWDq\" rel=\"noopener noreferrer\" target=\"_blank\">Video on my testing method, and mesuring device</a></span></div><div class=\"legend\"><span><i class=\"key single\"></i>Stiffness</span></div><div class=\"scroll\"><div id=\"stiffnessChart\"></div></div></section>\n<section class=\"card\"><h2>Fixture thermal deflection temperature</h2><div class=\"meta\"><span id=\"thermalCount\">Nearby BlueDOT probe-indicated fixture temperature</span><span>Comparative non-standard method; not ASTM D648, ISO 75, specimen temperature or certified HDT</span></div><div class=\"legend\"><span><i class=\"key single\"></i>Measured fixture temperature, °C</span></div><div class=\"scroll\"><div id=\"thermalChart\"></div></div></section>"),
            (
                "<option value=\"stiffness\">Stiffness, MPa</option>\n</select>\n</div>\n<div>\n<label>Comparison group</label>",
                "<option value=\"stiffness\">Stiffness, MPa</option>\n<option value=\"thermal\">Fixture thermal temperature, °C</option>\n</select>\n</div>\n<div>\n<label>Comparison group</label>"),
            (
                "if(metric==='stiffness')return row.stiffness?.value??null;",
                "if(metric==='stiffness')return row.stiffness?.value??null;\n if(metric==='thermal')return row.thermal?.value??null;"),
            (
                "if(metric.startsWith('impact'))return 'kJ/m²';\n return 'MPa';",
                "if(metric.startsWith('impact'))return 'kJ/m²';\n if(metric==='thermal')return '°C';\n return 'MPa';"),
            (
                "impactFlat:'Impact flat',impactUpright:'Impact upright',stiffness:'Stiffness'};",
                "impactFlat:'Impact flat',impactUpright:'Impact upright',stiffness:'Stiffness',thermal:'Fixture thermal temperature'};"),
            (
                "DATA.stiffness.forEach(r=>{ensure(r).stiffness=r;});\n return [...map.values()]",
                "DATA.stiffness.forEach(r=>{ensure(r).stiffness=r;});\n DATA.thermal.forEach(r=>{ensure(r).thermal=r;});\n return [...map.values()]"),
            (
                "apply(DATA.stiffness).forEach(r=>{ensure(r).stiffness=r;});\n return [...map.values()]",
                "apply(DATA.stiffness).forEach(r=>{ensure(r).stiffness=r;});\n apply(DATA.thermal).forEach(r=>{ensure(r).thermal=r;});\n return [...map.values()]"),
            (
                "function renderSingle(target,countId,rawRows,unit){",
                "function renderSingle(target,countId,rawRows,unit,metricName='Stiffness'){"),
            (
                "<br>Stiffness: ${fmt(val)} ${unit}",
                "<br>${esc(metricName)}: ${fmt(val)} ${unit}"),
            (
                "renderSingle('stiffnessChart','stiffnessCount',DATA.stiffness,'MPa');renderCombined();",
                "renderSingle('stiffnessChart','stiffnessCount',DATA.stiffness,'MPa');renderSingle('thermalChart','thermalCount',DATA.thermal,'°C','Fixture temperature');renderCombined();"),
            (
                "stiffness:avg(items.map(x=>x.stiffnessScore)),layer:avg(items.map(x=>x.layerAdhesionScore))",
                "stiffness:avg(items.map(x=>x.stiffnessScore)),thermal:avg(items.map(x=>x.thermalScore)),layer:avg(items.map(x=>x.layerAdhesionScore))"),
            (
                "<th>Impact</th><th>Stiffness</th><th>Layer adhesion</th><th>Consistency</th>",
                "<th>Impact</th><th>Stiffness</th><th>Thermal</th><th>Layer adhesion</th><th>Consistency</th>"),
            (
                "['overall','tensile','impact','stiffness','layer','consistency']",
                "['overall','tensile','impact','stiffness','thermal','layer','consistency']")
        };

        foreach (var replacement in replacements)
        {
            if (!html.Contains(replacement.Old, StringComparison.Ordinal))
                throw new InvalidOperationException("The active website template does not support the governed v61.0.7 thermal presentation contract.");
            html = html.Replace(replacement.Old, replacement.New, StringComparison.Ordinal);
        }

        return html.Replace("</script>", marker + "\n</script>", StringComparison.Ordinal);
    }

    private static string RemoveLegacyPricingOverlay(string template)
    {
        // v35.0 initially added pricing through a static PRICE_DATA object followed by
        // Object.assign(...). Native website DATA now carries the current pricing fields.
        // Keeping that legacy overlay would overwrite freshly exported prices with stale
        // values from the selected external template. Remove both pieces when present.
        var priceStart = Regex.Match(template, @"\bconst\s+PRICE_DATA\s*=");
        if (priceStart.Success)
        {
            var equalsIndex = template.IndexOf('=', priceStart.Index);
            var objectStart = equalsIndex >= 0 ? template.IndexOf('{', equalsIndex) : -1;
            var objectEnd = objectStart >= 0 ? FindMatchingJsonObjectEnd(template, objectStart) : -1;

            if (objectEnd >= 0)
            {
                var replaceEnd = objectEnd + 1;
                while (replaceEnd < template.Length && char.IsWhiteSpace(template[replaceEnd])) replaceEnd++;
                if (replaceEnd < template.Length && template[replaceEnd] == ';') replaceEnd++;
                while (replaceEnd < template.Length && (template[replaceEnd] == '\r' || template[replaceEnd] == '\n')) replaceEnd++;
                template = template.Substring(0, priceStart.Index) + template.Substring(replaceEnd);
            }
        }

        template = Regex.Replace(
            template,
            @"^[ \t]*Object\.values\(DATA\)\.forEach\(rows=>rows\.forEach\(r=>Object\.assign\(r,PRICE_DATA\[r\.materialId\]\|\|\{\}\)\)\);[ \t]*(?:\r?\n)?",
            string.Empty,
            RegexOptions.Multiline);

        return template;
    }

    public WebsiteHtmlRendererVerificationResult VerifyMainWebsitePayload(WebsiteChartPayload payload)
    {
        var result = new WebsiteHtmlRendererVerificationResult
        {
            TensileRows = payload.Tensile.Count,
            ImpactRows = payload.Impact.Count,
            StiffnessRows = payload.Stiffness.Count,
            ThermalRows = payload.Thermal.Count
        };

        result.HasDataPayload = result.TensileRows > 0 && result.ImpactRows > 0 && result.StiffnessRows > 0 && result.ThermalRows > 0;
        result.PayloadRowsAligned = result.TensileRows == result.ImpactRows &&
                                    result.TensileRows == result.StiffnessRows &&
                                    result.TensileRows == result.ThermalRows;
        result.HasMaterialIds = payload.Tensile.All(row => row.TryGetValue("materialId", out var value) && !string.IsNullOrWhiteSpace(value?.ToString()));
        result.HasChartMetrics = HasAnyMetric(payload.Tensile, "upright", "flat") ||
                                 HasAnyMetric(payload.Impact, "upright", "flat") ||
                                 HasAnyMetric(payload.Stiffness, "value") ||
                                 HasAnyMetric(payload.Thermal, "value");
        result.HasPricingFields = payload.Tensile.All(row => row.ContainsKey("msrpUsd") &&
                                                              row.ContainsKey("landedCostUsd") &&
                                                              row.ContainsKey("msrpUsdPerKg") &&
                                                              row.ContainsKey("landedCostUsdPerKg") &&
                                                              row.ContainsKey("pricingStatus"));
        result.HasThermalFields = payload.Tensile.All(row =>
            row.ContainsKey("thermalResultTemperatureC") && row.ContainsKey("thermalScore") &&
            row.ContainsKey("thermalMethodVersion") && row.ContainsKey("thermalLimitation"));
        result.TemplateDataBlockSupported = true;
        result.Passed = result.HasDataPayload && result.PayloadRowsAligned && result.HasMaterialIds && result.HasChartMetrics && result.HasPricingFields && result.HasThermalFields && result.TemplateDataBlockSupported;
        return result;
    }

    public bool HasDataBlock(string template)
    {
        if (string.IsNullOrEmpty(template)) return false;
        return Regex.IsMatch(template, @"\bconst\s+DATA\s*=");
    }

    private static string ReplaceDataBlock(string template, string dataJson)
    {
        var replacement = "const DATA=" + dataJson + ";";

        var dataStart = Regex.Match(template, @"\bconst\s+DATA\s*=");
        if (!dataStart.Success)
        {
            throw new InvalidOperationException("Could not locate the const DATA=... block in the website template.");
        }

        var equalsIndex = template.IndexOf('=', dataStart.Index);
        if (equalsIndex < 0)
        {
            throw new InvalidOperationException("Could not locate the const DATA=... block in the website template.");
        }

        var objectStart = template.IndexOf('{', equalsIndex);
        if (objectStart < 0)
        {
            throw new InvalidOperationException("Could not locate the opening JSON object for const DATA in the website template.");
        }

        var objectEnd = FindMatchingJsonObjectEnd(template, objectStart);
        if (objectEnd < 0)
        {
            throw new InvalidOperationException("Could not locate the end of the const DATA JSON object in the website template.");
        }

        var replaceEnd = objectEnd + 1;
        while (replaceEnd < template.Length && char.IsWhiteSpace(template[replaceEnd])) replaceEnd++;
        if (replaceEnd < template.Length && template[replaceEnd] == ';') replaceEnd++;

        var lineEnding = Environment.NewLine;
        if (replaceEnd < template.Length && template[replaceEnd] == '\r')
        {
            replaceEnd++;
            if (replaceEnd < template.Length && template[replaceEnd] == '\n') replaceEnd++;
            lineEnding = "\r\n";
        }
        else if (replaceEnd < template.Length && template[replaceEnd] == '\n')
        {
            replaceEnd++;
            lineEnding = "\n";
        }

        return template.Substring(0, dataStart.Index) + replacement + lineEnding + template.Substring(replaceEnd);
    }

    private static int FindMatchingJsonObjectEnd(string text, int objectStart)
    {
        var depth = 0;
        var inString = false;
        var escape = false;

        for (var i = objectStart; i < text.Length; i++)
        {
            var ch = text[i];
            if (inString)
            {
                if (escape) { escape = false; continue; }
                if (ch == '\\') { escape = true; continue; }
                if (ch == '"') inString = false;
                continue;
            }

            if (ch == '"') { inString = true; continue; }
            if (ch == '{') { depth++; continue; }
            if (ch == '}')
            {
                depth--;
                if (depth == 0) return i;
            }
        }

        return -1;
    }

    private static bool HasAnyMetric(IReadOnlyList<Dictionary<string, object?>> rows, params string[] metricKeys)
    {
        return rows.Any(row => metricKeys.Any(key => row.TryGetValue(key, out var value) && IsNumeric(value)));
    }

    private static bool IsNumeric(object? value)
    {
        return value switch
        {
            null => false,
            int => true,
            long => true,
            float f => float.IsFinite(f),
            double d => double.IsFinite(d),
            decimal => true,
            _ => double.TryParse(value.ToString(), out var parsed) && double.IsFinite(parsed)
        };
    }
}

public sealed class WebsiteHtmlRendererVerificationResult
{
    public bool Passed { get; set; }
    public int TensileRows { get; set; }
    public int ImpactRows { get; set; }
    public int StiffnessRows { get; set; }
    public int ThermalRows { get; set; }
    public bool HasDataPayload { get; set; }
    public bool PayloadRowsAligned { get; set; }
    public bool HasMaterialIds { get; set; }
    public bool HasChartMetrics { get; set; }
    public bool HasPricingFields { get; set; }
    public bool HasThermalFields { get; set; }
    public bool TemplateDataBlockSupported { get; set; }
}
